### PR TITLE
Issue #15

### PR DESCRIPTION
**Pull request by scho**
Hi Ben,

I've fixed issue #15 and also added some cucumber steps to open and close nodes in a data grid.

Would be nice, to see this in the 'official' melomel :)

cheers,

Georg

### CODE REVIEW

**Comment by benbjohnson** [comment]
Awesome. Thanks! I push a new release of the gem (v0.6.5) with the changes. Let me know if it works for you.

**Comment by scho** [comment]
Hi,

v0.6.5 works great for me. But I'm still not so satisfied with the API. If you come up with better naming of the methods in Melomel::Cucumber, please change it. 

And by the way, I tried to consider visibility of columns as well, but then I found out, that if you compare two columns, you can leave out entire columns and it won't trow an error. So invisible columns aren't a problem.

**Comment by laran** [comment]
It looks like the code I need to get AdvancedDataGrids working better might be in @scho's commit. I just uninstalled and then installed v 0.6.5 of the melomel gem. But scho's fix isn't in there. What am I missing?

**Comment by benbjohnson** [comment]
I just pulled down the gem and I see @scho's changes in data_grid_steps.rb. 

Do you have any other versions of the Melomel gem installed? Check it with the `gem list melomel` command.

If you do have any others installed, remove them using the `gem uninstall melomel` command. It'll ask you which version if you have multiple.

Also, where are you looking to find the gem's code?

**Comment by laran** [comment]
I figured it out. I had forgotten to update my bundle and still have 0.6.4 in there. I changed that to 0.6.5 and ran bundle update, then it worked. As for why I couldn't see the changes in the code, I was just looking in the wrong place.

So, it's working now. I'm getting my data rows. Yay!

**Comment by benbjohnson** [comment]
Yay! That's awesome. I'm glad it got worked out.

**Pull request merged**
